* Dotfiles

Some configuration files I use on multiple machines.

** Bash
   Collection of bash functions/aliases/settings I use. Bulk of functions are in [[file:bash/main.sh][main.sh]], with private stuff in [[file:bash/private.sh][private.sh]] (obviously not tracked by git), and a utility library in utils which defines some useful functions for scripting rather than regular usage. If [[file:bash/main.sh][main.sh]] ever gets too disorganized, I'll likely branch it into functions.sh, aliases.sh, etc. Full credit for library functions goes to [[https://www.nostarch.com/wicked2][Wicked Cool Shell Scripts, 2nd Edition]]. I source all of these into my session at startup through the following code in my ~/.bashrc:

   #+BEGIN_SRC sh
     # Load in my custom configuration
     if [[ -d ~/dotfiles/bash ]]; then
         # Load util library functions first
         for util in ~/dotfiles/bash/utils/library/*; do
             . "$util"
         done
         # Load util scripts
         export PATH="$PATH:~/dotfiles/bash/utils/scripts"
         # Now rest of the files
         for file in ~/dotfiles/bash/*; do
             if [[ ! -d $file ]]; then
                 . "$file"
             fi
         done
     fi
   #+END_SRC

** Vim
   vim configuration file. ~/.vimrc is a symlink to this

** Spacemacs
  [[http://spacemacs.org/][Spacemacs]] configuration. Uses symlinks similar to with vim above.
